### PR TITLE
Rename ReadableByteStream to ReadableStream. Add a note.

### LINKED ISSUE #46: Change type to ReadableStream
@domenic and @wanderview arrived at using `ReadableStream` for now. But we should have a note that indicates it might become `ReadableByteStream` if that path doesn't work out.

### PR DESCRIPTION
**Pull request by yutakahirano**
For #46.

### CODE REVIEW

**Comment by yutakahirano** [comment]
@annevk, @domenic, can you take a look?

**Comment by annevk** [comment]
So I think some of this needs to move to IDL, since otherwise it doesn't work technically. You can't really mix operations on IDL objects and JavaScript objects freely like that.

Otherwise this seems fine. The harder aspect is when the stream is controlled by the developer.

**Comment by yutakahirano** [comment]
Fixed IDL.

> I think some of this needs to move to IDL, since otherwise it doesn't work technically. You can't really mix operations on IDL objects and JavaScript objects freely like that.

Sorry I don't understand. Can you give an example?

**Comment by annevk** [comment]
What we return is an IDL `ReadableStream`. What JavaScript sees is a JavaScript `ReadableStream`. IDL needs to be updated to handle this. I filed https://www.w3.org/Bugs/Public/show_bug.cgi?id=28988 a while ago to get this added by the way.

(To even use `ReadableStream` in IDL, it needs to be listed there.)

**Comment by yutakahirano** [comment]
Thanks.

Then operations such as construction, en-queuing, closing, etc. will be defined in WebIDL, right? Will dependency to the Streams spec be replaced by dependency to WebIDL?

**Comment by annevk** [comment]
Yeah, sounds about right.

**Comment by domenic** [comment]
This seems good but I think we should add a note about ReadableStream vs. ReadableByteStream as I kind of said in #46. I will try to draft such a note later.

> Then operations such as construction, en-queuing, closing, etc. will be defined in WebIDL, right? Will dependency to the Streams spec be replaced by dependency to WebIDL?

This seems kind of sucky. Web IDL should not need to be updated in such close tandem with the operations on streams. My preference would be, from most preferable to least:

- Add a note in fetch-with-streams saying we are somewhat loose with IDL type vs. JS type, but that converting between them should be done in the obvious way.
- Have fetch-with-streams use some more explicit convention, like EnqueueInReadableStream(ToJSObject(idlReadableStream)) or "let _jsrs_ be the JavaScript value for the IDL value _rs_".
- Have Streams define all these types of operations in its own section. I am thinking maybe EnqueueInIDLReadableStream(idlRS, idlObject): convert idlRS to a JS object; convert idlObject to a JS object; run EnqueueInReadableStream(converted args). Repeat ad-naseum.

The additions to Web IDL should be minor. I am thinking just the two type conversion rules.

Also, I do think maybe streams should incorporate the "to construct a fixed ReadableStream" or "to construct an empty ReadableStream." I can try to move those over to streams. They would operate on JS objects by default though.

**Comment by annevk** [comment]
With JavaScript IDL had to take care of all the conversions. Now we define JavaScript features outside of JavaScript, perhaps both could carry some weight as you suggest. I would prefer us to be formally correct, but I'm okay with short term hacks.

**Comment by yutakahirano** [comment]
Thanks, @domenic, I added description about Readable[Byte]Stream.

I filed a new issue #51 for ReadableStream distinction.

**Comment by yutakahirano** [comment]
Thanks!

**Pull request merged**
