### PR TITLE
Add a link to the stream spec for body teeing.

### PR DESCRIPTION
**Pull request by yutakahirano**

### CODE REVIEW

**Comment by yutakahirano** [comment]
This fixes #14. @domenic, can you take a look?

**Comment by domenic** [comment]
LGTM. Minor nits: I would do

> Let «out1, out2» be [TeeReadableStream](https://streams.spec.whatwg.org/#tee-readable-stream)(the associated readable stream, __true__)

Justification: TeeReadableStream returns a list, which uses «» instead of \[\] (which is for arrays), and in #28 I use the function-call-style syntax for abstract ops so using it here to match seems nice.

**Comment by annevk** [comment]
However, Fetch currently does not use such syntax...

**Comment by domenic** [comment]
I mean, Fetch doesn't have abstract operations. In the end it's an integration point between two specs, so you have to pick a calling convention and stick with it.

**Comment by annevk** [comment]
Fair, hopefully we can converge on something over time, but I guess once I attempt the merge with Fetch I can call out the differences in notes while we're in a transitional time.

**Comment by domenic** [comment]
Yeah, I guess I just don't really see a problem with using another spec's notation when calling into another spec, even if that notation is different from what is used internally.

**Comment by yutakahirano** [comment]
Thanks, fixed.

**Pull request merged**
