### PR TITLE
Describe auto-termination more implicitly #15

### PR DESCRIPTION
**Pull request by yutakahirano**
Instead of describe conditions explicitely, describe them in a more implicit
way in order to allow implementers' optimizations.

### CODE REVIEW

**Comment by yutakahirano** [comment]
@domenic @annevk @wanderview Can you take a look?

**Comment by yutakahirano** [comment]
@domenic @wanderview do you have any comments?

**Comment by wanderview** [comment]
I will look tomorrow.

**Comment by wanderview** [comment]
Looks great!  Thanks for doing this!

**Comment by domenic** [comment]
LGTM.

**Comment by yutakahirano** [comment]
Thanks for the review!

**Pull request merged**
