### PR TITLE
Specify body stream chunk type.

### PR DESCRIPTION
**Pull request by yutakahirano**

### CODE REVIEW

**Comment by annevk** [comment]
Why a view upon a buffer rather than a buffer directly?

**Comment by annevk** [comment]
The Encoding Standard does the same thing and I think we sort of regret it now.

**Comment by yutakahirano** [comment]
ReadableByteStream BYOB reader accepts and returns ArrayBufferView and ReadableByteStream default buffer returns Uint8ArrayBuffer to match that. Can you tell me why you regret using ArrayBufferView?

**Comment by annevk** [comment]
There's a number of APIs that directly expose the buffer (`fetch()`, WebSocket, ?) that leave the view up to the consumer. It's unclear why we should pick a view for the consumer.

**Pull request merged**
