### PR TITLE
Define ReadableByteStream[Reader].

### PR DESCRIPTION
**Pull request by yutakahirano**
@wanderview, @domenic, @tyoshino, @kenjibaheux Can I define ReadableByteStream[Reader] here as a workaround for the [concern] (https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/35_QSL1ABTY)?

### CODE REVIEW

**Comment by yutakahirano** [comment]
Justification: We are sure that a ReadableByteStream can be used as a ReadableStream from the user-side.

**Comment by tyoshino** [comment]
lgtm

**Comment by domenic** [comment]
LGTM too. @wanderview does this help?

**Comment by wanderview** [comment]
That does definitely help.  Thanks!

I would still personally just use ReadableStream for now, but this is probably adequate if you are ok locking yourself into the superset requirement.

**Pull request merged**
